### ISSUE TITLE
QStandardPaths: XDG_RUNTIME_DIR not set, defaulting to '/tmp/runtime-root'

### ISSUE THREAD

**Issue by darkhacknet** [shiky8/SigFramework#1]
Hello my Fiend, this is awesome, thanks for this great work. 

I need to mention that we are facing this "issue" or "warning" about this specific line:

QStandardPaths: XDG_RUNTIME_DIR not set, defaulting to '/tmp/runtime-root'

Which is displayed after send the command "sudo python3 sigfremwork_gui_main.py"

When I send the command without "sudo" everything looks good. But It will be better to avoid the warning correctly, could you please tell me how to fix this ? 

Thanks in advance.
Kind regards !

**Comment by shiky8** [comment]
Hi  darkhacknet

Add   this line to /etc/sudoers

Defaults        env_keep += "XDG_RUNTIME_DIR"

OR use  -E

" sudo -E python3 sigfremwork_gui_main.py "

But the tool will run fine with the warning

**Comment by darkhacknet** [comment]
> Hi  darkhacknet
> 
> Add   this line to /etc/sudoers
> 
> Defaults        env_keep += "XDG_RUNTIME_DIR"
> 
> OR use  -E
> 
> " sudo -E python3 sigfremwork_gui_main.py "
> 
> But the tool will run fine with the warning
> 

Thank you so much for the quick response, and yes.. Of course its working with the warning. I was avoiding to install the precise requirements versions, but with this lines it will be better.

I'll continúe testing. Thanks 👌
